name: NEW OWASP ZAP
on: [workflow_dispatch]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable
      - name: Create ZAP Working Directory (with write access)
        run: mkdir -p zap_wrk
      - name: test file
        run: echo "test file" > testfile.html
      - name: upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Report
          path: zap_report.html
