name: NEW OWASP ZAP
on: workflow_dispatch
jobs:
  zap_scan:
    runs-on: ubuntu-latest  # You can specify a different runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from your repository

      - name: Pull ZAP Docker image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable  # Download the stable ZAP image

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0  # Use the ZAP Baseline action
        with:
          target: 'https://stackfactor.ai' 
          # Optional arguments (uncomment and adjust as needed)
          # token: ${{ secrets.GITHUB_TOKEN }}  # Use a secret for token
          # docker_name: 'ghcr.io/zaproxy/zaproxy:weekly'  # Use weekly build
          # rules_file_name: '.zap/rules.tsv'  # Specify a rules file path
          # cmd_options: '-a'  # Additional command line options
          # allow_issue_writing: false  # Disable issue creation
          # issue_title: 'ZAP Scan Report'  # Custom title for issues
          # fail_action: true  # Fail workflow on alerts
          # artifact_name: 'my-zap-report'  # Custom artifact name

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: zap_scan.html  # Adjust path if using a different output file
