name: OWASP ZAP
on: 
 push:
 workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log current directory
        run: echo ${pwd}
      - name: Pull ZAP Idocker Image
        run: docker pull owasp/zap2docker-weekly
      - name: Run ZAP SCcan 
        run: |
          docker run -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py -t http://cyberpupps.com -r report.html
    
