name: OWASP ZAP
on: 
 push:
 workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull ZAP Idocker Image
        run: docker pull owasp/zap2docker-stable
	     - name: executePWD
		      run: pwd
      - name: Run ZAP SCcan 
        run: docker run -v $(pwd):/zap/wrk:rw --user root -t owasp/zap2docker-stable zap-baseline.py -t http://testphp.vulnweb.com -r testPhp_report.html
