
name: OWASP ZAP
on: 
 push:
 workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull ZAP Idocker Image
        run: docker pull owasp/zap2docker-stable
      - name: Run ZAP SCcan 
        run: |
         docker run -v $(pwd):/zap/wrk/:rw -t ubuntu:20.04 touch /zap/wrk/test.txt

         
