name: OWASP ZAP
on: [workflow_dispatch]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Create ZAP Working Directory
        run: mkdir -p zap_wrk

      - name: Run ZAP Baseline Scan
        run: docker run -v ${{ github.workspace }}:/zap/wrk/:rw --user root -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -c /zap/wrk/rules.tsv -t https://qa.stackfactor.ai -r zap_wrk/zap_report.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Report
          path: zap_wrk/zap_report.html

