
name: OWASP ZAP
on: 
 push:
 workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: "https://stackfactor.ai"
         
