
name: OWASP ZAP
on: 
 push:
 workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Run ZAP Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          target: "https://cyberpupps.com"
         
